sudo: false
language: python
python:
  - "3.6"
cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TZ=UTC

install:
  - pip install twine
  - pip install --upgrade pip --cache-dir $HOME/.pip-cache/
  - pip install coveralls coverage --cache-dir $HOME/.pip-cache/
  - pip install flake8 --cache-dir $HOME/.pip-cache/
  - pip install -r requirements-dev.txt --cache-dir $HOME/.pip-cache/
  - pip install -e . --cache-dir $HOME/.pip-cache/
script:
  - flake8 molo
  - molo scaffold testapp --require molo.pwa --include molo.pwa ^pwa/
  - flake8 testapp
  - cp test_settings.py testapp/testapp/settings/local.py
  - pip install -e testapp
  - py.test --cov=molo.pwa --cov-report=term

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: praekelt.org
  password:
    secure: UjvjRi0s2i/qwDxThmRtYV9kdkeu+uSmUBow0dTnTFFGvpPpyIHb3Fjy/X8NeVCtBss/E8G4hX8HHIZamW/zhDfeMp/AMrqwL6lKzxy1LDknXXbtYCW+R5DfN2cyYK1qk/nloxhOniPf0zIjmtRUxkvsbwx+T6uX6Uwa5NS8mXPl89sys/5xfiJHK+tjLCAQq9Z7BOu58loHpEwcZcyow9EsO9MA/HjceJLGSycttg7iiUod9qzGNxt/yOU+ysE95grwy0/jKil/FNnB6O9jSHNjjgKy7oYB4zLGlgu8V+t1vsLYnYGLkxajjPEMqOKt/CT7vToRV9vqy/IUK2wkvroQn7eKc3cpIx+9VDvrqudmx5W/b07iW8fymWo06nxAhU90lpGVU9ce44Ni60Z09GyXQ2Dtx4x+Rl3HAq/WhWH9AfmLJi82YL/pnZBVDJETTtg+CTdNkCWnaKjzr2n4kY+zKQsp+rZ943mPWo9nMUcvifmyYUV51PkT5AoIdjmRBnlFZ71Rydwt0TNSpzVEY0DOhgJmuZXZ8XU0x11AANXdh4EF+c8+myvjHuoe1No/xjwDD1v3ZW4fMLEhkXO8F+Qn+pgcbzI+XH2a32nhop8HNEa77LbwJ1KtvPLkkK0xRVhJmkdn4duGx923s+D0g1fNpes+nS6XgfwlwXXL56w=
  on:
    tags: true
    all_branches: true
