sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TZ=UTC

install:
  - pip install twine
  - pip install --upgrade pip --cache-dir $HOME/.pip-cache/
  - pip install coveralls coverage --cache-dir $HOME/.pip-cache/
  - pip install flake8 --cache-dir $HOME/.pip-cache/
  - pip install -r requirements-dev.txt --cache-dir $HOME/.pip-cache/
  - pip install -e . --cache-dir $HOME/.pip-cache/
script:
  - flake8 molo
  - molo scaffold testapp --require molo.pwa --include molo.pwa ^pwa/
  - flake8 testapp
  - pip install -e testapp
  - py.test --cov=molo.pwa --cov-report=term

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Praekelt
  password:
    secure: "jTQHZlI3YyLehVmmaLfAdf9WrUCjuhIIuSiBmtT5MtspxZrfkq5HEvQbaB6amfrFhniuVIrL4QLGkcyKU5WR5OFZU4chnLhvuklusuWQu/BjOVT3h9Qd6o0xT9rZ/ZWODe0F+blpAciN9P8YF95nWmmJQew6/SNvnRbRfcbY9dxFPkCxwt1vzKkFzqfTJvVpv0sw0IkUKX4N6EbaJNTU8M+3pqmEfh28TEVi6uQiLJMQ66rRRG13WizIOpkBdOos+yn1kkAG4/S64QT5mJekEjmMKYk4CP//PuHuNGXIFjaJWRQQMqIJjwNQIpVMuOcUVm5x9jvUSYI5Dm9D664lA+u4Sh0prZj2gXhWgc7qjQKCwEQuKxPsLQYSU31l/FaRSJC3DLPAFcIIBmYd6jUVPEY4OvEdykQAgu8LMtJiPd8Wn7u41ZWxMXqSU9xEAEChAAGmAxLapJxvftHz+XFiFvLCB8duTDnlrCA39hdPe9oqzK6ghidmO36P94bGjdGS/uyzMG9uNY0toKCxA58ve4sfrMMWlbMJIij7AQFDdMxmx9kdb+udsU6EHOtlEVXwOzdtuYeJkB8zeXAdPqZsy7YQfQ+vuQRoZERKE2p543JknKD+GIFUgP8cySHUmM2A4pu89ZFTGtZkP3VxBZ34pNwvzCRsPrjNWUSyTaxSjao="
  on:
    tags: true
    all_branches: true
